/*
 * Generated by gdbus-codegen 2.48.2. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif

#include "ServiceOfSerial.h"

#include <string.h>
#ifdef G_OS_UNIX
#  include <gio/gunixfdlist.h>
#endif

typedef struct
{
  GDBusArgInfo parent_struct;
  gboolean use_gvariant;
} _ExtendedGDBusArgInfo;

typedef struct
{
  GDBusMethodInfo parent_struct;
  const gchar *signal_name;
  gboolean pass_fdlist;
} _ExtendedGDBusMethodInfo;

typedef struct
{
  GDBusSignalInfo parent_struct;
  const gchar *signal_name;
} _ExtendedGDBusSignalInfo;

typedef struct
{
  GDBusPropertyInfo parent_struct;
  const gchar *hyphen_name;
  gboolean use_gvariant;
} _ExtendedGDBusPropertyInfo;

typedef struct
{
  GDBusInterfaceInfo parent_struct;
  const gchar *hyphen_name;
} _ExtendedGDBusInterfaceInfo;

typedef struct
{
  const _ExtendedGDBusPropertyInfo *info;
  guint prop_id;
  GValue orig_value; /* the value before the change */
} ChangedProperty;

static void
_changed_property_free (ChangedProperty *data)
{
  g_value_unset (&data->orig_value);
  g_free (data);
}

static gboolean
_g_strv_equal0 (gchar **a, gchar **b)
{
  gboolean ret = FALSE;
  guint n;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  if (g_strv_length (a) != g_strv_length (b))
    goto out;
  for (n = 0; a[n] != NULL; n++)
    if (g_strcmp0 (a[n], b[n]) != 0)
      goto out;
  ret = TRUE;
out:
  return ret;
}

static gboolean
_g_variant_equal0 (GVariant *a, GVariant *b)
{
  gboolean ret = FALSE;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  ret = g_variant_equal (a, b);
out:
  return ret;
}

G_GNUC_UNUSED static gboolean
_g_value_equal (const GValue *a, const GValue *b)
{
  gboolean ret = FALSE;
  g_assert (G_VALUE_TYPE (a) == G_VALUE_TYPE (b));
  switch (G_VALUE_TYPE (a))
    {
      case G_TYPE_BOOLEAN:
        ret = (g_value_get_boolean (a) == g_value_get_boolean (b));
        break;
      case G_TYPE_UCHAR:
        ret = (g_value_get_uchar (a) == g_value_get_uchar (b));
        break;
      case G_TYPE_INT:
        ret = (g_value_get_int (a) == g_value_get_int (b));
        break;
      case G_TYPE_UINT:
        ret = (g_value_get_uint (a) == g_value_get_uint (b));
        break;
      case G_TYPE_INT64:
        ret = (g_value_get_int64 (a) == g_value_get_int64 (b));
        break;
      case G_TYPE_UINT64:
        ret = (g_value_get_uint64 (a) == g_value_get_uint64 (b));
        break;
      case G_TYPE_DOUBLE:
        {
          /* Avoid -Wfloat-equal warnings by doing a direct bit compare */
          gdouble da = g_value_get_double (a);
          gdouble db = g_value_get_double (b);
          ret = memcmp (&da, &db, sizeof (gdouble)) == 0;
        }
        break;
      case G_TYPE_STRING:
        ret = (g_strcmp0 (g_value_get_string (a), g_value_get_string (b)) == 0);
        break;
      case G_TYPE_VARIANT:
        ret = _g_variant_equal0 (g_value_get_variant (a), g_value_get_variant (b));
        break;
      default:
        if (G_VALUE_TYPE (a) == G_TYPE_STRV)
          ret = _g_strv_equal0 (g_value_get_boxed (a), g_value_get_boxed (b));
        else
          g_critical ("_g_value_equal() does not handle type %s", g_type_name (G_VALUE_TYPE (a)));
        break;
    }
  return ret;
}

/* ------------------------------------------------------------------------
 * Code for interface Serial.interface
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:SerialInterface
 * @title: SerialInterface
 * @short_description: Generated C code for the Serial.interface D-Bus interface
 *
 * This section contains code for working with the <link linkend="gdbus-interface-Serial-interface.top_of_page">Serial.interface</link> D-Bus interface in C.
 */

/* ---- Introspection data for Serial.interface ---- */

static const _ExtendedGDBusArgInfo _serial_interface_method_info_set_door_info_IN_ARG_arg1 =
{
  {
    -1,
    (gchar *) "arg1",
    (gchar *) "q",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _serial_interface_method_info_set_door_info_IN_ARG_arg2 =
{
  {
    -1,
    (gchar *) "arg2",
    (gchar *) "q",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _serial_interface_method_info_set_door_info_IN_ARG_pointers[] =
{
  &_serial_interface_method_info_set_door_info_IN_ARG_arg1,
  &_serial_interface_method_info_set_door_info_IN_ARG_arg2,
  NULL
};

static const _ExtendedGDBusArgInfo _serial_interface_method_info_set_door_info_OUT_ARG_unnamed_arg2 =
{
  {
    -1,
    (gchar *) "unnamed_arg2",
    (gchar *) "b",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _serial_interface_method_info_set_door_info_OUT_ARG_pointers[] =
{
  &_serial_interface_method_info_set_door_info_OUT_ARG_unnamed_arg2,
  NULL
};

static const _ExtendedGDBusMethodInfo _serial_interface_method_info_set_door_info =
{
  {
    -1,
    (gchar *) "setDoorInfo",
    (GDBusArgInfo **) &_serial_interface_method_info_set_door_info_IN_ARG_pointers,
    (GDBusArgInfo **) &_serial_interface_method_info_set_door_info_OUT_ARG_pointers,
    NULL
  },
  "handle-set-door-info",
  FALSE
};

static const _ExtendedGDBusArgInfo _serial_interface_method_info_set_lamp_info_IN_ARG_arg1 =
{
  {
    -1,
    (gchar *) "arg1",
    (gchar *) "q",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _serial_interface_method_info_set_lamp_info_IN_ARG_arg2 =
{
  {
    -1,
    (gchar *) "arg2",
    (gchar *) "q",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _serial_interface_method_info_set_lamp_info_IN_ARG_pointers[] =
{
  &_serial_interface_method_info_set_lamp_info_IN_ARG_arg1,
  &_serial_interface_method_info_set_lamp_info_IN_ARG_arg2,
  NULL
};

static const _ExtendedGDBusArgInfo _serial_interface_method_info_set_lamp_info_OUT_ARG_unnamed_arg2 =
{
  {
    -1,
    (gchar *) "unnamed_arg2",
    (gchar *) "b",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _serial_interface_method_info_set_lamp_info_OUT_ARG_pointers[] =
{
  &_serial_interface_method_info_set_lamp_info_OUT_ARG_unnamed_arg2,
  NULL
};

static const _ExtendedGDBusMethodInfo _serial_interface_method_info_set_lamp_info =
{
  {
    -1,
    (gchar *) "setLampInfo",
    (GDBusArgInfo **) &_serial_interface_method_info_set_lamp_info_IN_ARG_pointers,
    (GDBusArgInfo **) &_serial_interface_method_info_set_lamp_info_OUT_ARG_pointers,
    NULL
  },
  "handle-set-lamp-info",
  FALSE
};

static const _ExtendedGDBusArgInfo _serial_interface_method_info_set_key_info_IN_ARG_arg1 =
{
  {
    -1,
    (gchar *) "arg1",
    (gchar *) "q",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _serial_interface_method_info_set_key_info_IN_ARG_arg2 =
{
  {
    -1,
    (gchar *) "arg2",
    (gchar *) "q",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _serial_interface_method_info_set_key_info_IN_ARG_pointers[] =
{
  &_serial_interface_method_info_set_key_info_IN_ARG_arg1,
  &_serial_interface_method_info_set_key_info_IN_ARG_arg2,
  NULL
};

static const _ExtendedGDBusArgInfo _serial_interface_method_info_set_key_info_OUT_ARG_unnamed_arg2 =
{
  {
    -1,
    (gchar *) "unnamed_arg2",
    (gchar *) "b",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _serial_interface_method_info_set_key_info_OUT_ARG_pointers[] =
{
  &_serial_interface_method_info_set_key_info_OUT_ARG_unnamed_arg2,
  NULL
};

static const _ExtendedGDBusMethodInfo _serial_interface_method_info_set_key_info =
{
  {
    -1,
    (gchar *) "setKeyInfo",
    (GDBusArgInfo **) &_serial_interface_method_info_set_key_info_IN_ARG_pointers,
    (GDBusArgInfo **) &_serial_interface_method_info_set_key_info_OUT_ARG_pointers,
    NULL
  },
  "handle-set-key-info",
  FALSE
};

static const _ExtendedGDBusArgInfo _serial_interface_method_info_set_speed_info_IN_ARG_arg1 =
{
  {
    -1,
    (gchar *) "arg1",
    (gchar *) "q",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _serial_interface_method_info_set_speed_info_IN_ARG_arg2 =
{
  {
    -1,
    (gchar *) "arg2",
    (gchar *) "q",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _serial_interface_method_info_set_speed_info_IN_ARG_arg3 =
{
  {
    -1,
    (gchar *) "arg3",
    (gchar *) "q",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _serial_interface_method_info_set_speed_info_IN_ARG_pointers[] =
{
  &_serial_interface_method_info_set_speed_info_IN_ARG_arg1,
  &_serial_interface_method_info_set_speed_info_IN_ARG_arg2,
  &_serial_interface_method_info_set_speed_info_IN_ARG_arg3,
  NULL
};

static const _ExtendedGDBusArgInfo _serial_interface_method_info_set_speed_info_OUT_ARG_unnamed_arg3 =
{
  {
    -1,
    (gchar *) "unnamed_arg3",
    (gchar *) "b",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _serial_interface_method_info_set_speed_info_OUT_ARG_pointers[] =
{
  &_serial_interface_method_info_set_speed_info_OUT_ARG_unnamed_arg3,
  NULL
};

static const _ExtendedGDBusMethodInfo _serial_interface_method_info_set_speed_info =
{
  {
    -1,
    (gchar *) "setSpeedInfo",
    (GDBusArgInfo **) &_serial_interface_method_info_set_speed_info_IN_ARG_pointers,
    (GDBusArgInfo **) &_serial_interface_method_info_set_speed_info_OUT_ARG_pointers,
    NULL
  },
  "handle-set-speed-info",
  FALSE
};

static const _ExtendedGDBusArgInfo _serial_interface_method_info_set_air_conditioner_info_IN_ARG_arg1 =
{
  {
    -1,
    (gchar *) "arg1",
    (gchar *) "q",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _serial_interface_method_info_set_air_conditioner_info_IN_ARG_arg2 =
{
  {
    -1,
    (gchar *) "arg2",
    (gchar *) "q",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _serial_interface_method_info_set_air_conditioner_info_IN_ARG_arg3 =
{
  {
    -1,
    (gchar *) "arg3",
    (gchar *) "q",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _serial_interface_method_info_set_air_conditioner_info_IN_ARG_pointers[] =
{
  &_serial_interface_method_info_set_air_conditioner_info_IN_ARG_arg1,
  &_serial_interface_method_info_set_air_conditioner_info_IN_ARG_arg2,
  &_serial_interface_method_info_set_air_conditioner_info_IN_ARG_arg3,
  NULL
};

static const _ExtendedGDBusArgInfo _serial_interface_method_info_set_air_conditioner_info_OUT_ARG_unnamed_arg3 =
{
  {
    -1,
    (gchar *) "unnamed_arg3",
    (gchar *) "b",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _serial_interface_method_info_set_air_conditioner_info_OUT_ARG_pointers[] =
{
  &_serial_interface_method_info_set_air_conditioner_info_OUT_ARG_unnamed_arg3,
  NULL
};

static const _ExtendedGDBusMethodInfo _serial_interface_method_info_set_air_conditioner_info =
{
  {
    -1,
    (gchar *) "setAirConditionerInfo",
    (GDBusArgInfo **) &_serial_interface_method_info_set_air_conditioner_info_IN_ARG_pointers,
    (GDBusArgInfo **) &_serial_interface_method_info_set_air_conditioner_info_OUT_ARG_pointers,
    NULL
  },
  "handle-set-air-conditioner-info",
  FALSE
};

static const _ExtendedGDBusArgInfo _serial_interface_method_info_set_start_info_IN_ARG_arg1 =
{
  {
    -1,
    (gchar *) "arg1",
    (gchar *) "y",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _serial_interface_method_info_set_start_info_IN_ARG_pointers[] =
{
  &_serial_interface_method_info_set_start_info_IN_ARG_arg1,
  NULL
};

static const _ExtendedGDBusArgInfo _serial_interface_method_info_set_start_info_OUT_ARG_unnamed_arg1 =
{
  {
    -1,
    (gchar *) "unnamed_arg1",
    (gchar *) "b",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _serial_interface_method_info_set_start_info_OUT_ARG_pointers[] =
{
  &_serial_interface_method_info_set_start_info_OUT_ARG_unnamed_arg1,
  NULL
};

static const _ExtendedGDBusMethodInfo _serial_interface_method_info_set_start_info =
{
  {
    -1,
    (gchar *) "setStartInfo",
    (GDBusArgInfo **) &_serial_interface_method_info_set_start_info_IN_ARG_pointers,
    (GDBusArgInfo **) &_serial_interface_method_info_set_start_info_OUT_ARG_pointers,
    NULL
  },
  "handle-set-start-info",
  FALSE
};

static const _ExtendedGDBusMethodInfo * const _serial_interface_method_info_pointers[] =
{
  &_serial_interface_method_info_set_door_info,
  &_serial_interface_method_info_set_lamp_info,
  &_serial_interface_method_info_set_key_info,
  &_serial_interface_method_info_set_speed_info,
  &_serial_interface_method_info_set_air_conditioner_info,
  &_serial_interface_method_info_set_start_info,
  NULL
};

static const _ExtendedGDBusArgInfo _serial_interface_signal_info_broadcast_caninfo_ARG_candata =
{
  {
    -1,
    (gchar *) "candata",
    (gchar *) "ay",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _serial_interface_signal_info_broadcast_caninfo_ARG_len =
{
  {
    -1,
    (gchar *) "len",
    (gchar *) "y",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _serial_interface_signal_info_broadcast_caninfo_ARG_pointers[] =
{
  &_serial_interface_signal_info_broadcast_caninfo_ARG_candata,
  &_serial_interface_signal_info_broadcast_caninfo_ARG_len,
  NULL
};

static const _ExtendedGDBusSignalInfo _serial_interface_signal_info_broadcast_caninfo =
{
  {
    -1,
    (gchar *) "broadcastCANInfo",
    (GDBusArgInfo **) &_serial_interface_signal_info_broadcast_caninfo_ARG_pointers,
    NULL
  },
  "broadcast-caninfo"
};

static const _ExtendedGDBusSignalInfo * const _serial_interface_signal_info_pointers[] =
{
  &_serial_interface_signal_info_broadcast_caninfo,
  NULL
};

static const _ExtendedGDBusInterfaceInfo _serial_interface_interface_info =
{
  {
    -1,
    (gchar *) "Serial.interface",
    (GDBusMethodInfo **) &_serial_interface_method_info_pointers,
    (GDBusSignalInfo **) &_serial_interface_signal_info_pointers,
    NULL,
    NULL
  },
  "serial-interface",
};


/**
 * serial_interface_interface_info:
 *
 * Gets a machine-readable description of the <link linkend="gdbus-interface-Serial-interface.top_of_page">Serial.interface</link> D-Bus interface.
 *
 * Returns: (transfer none): A #GDBusInterfaceInfo. Do not free.
 */
GDBusInterfaceInfo *
serial_interface_interface_info (void)
{
  return (GDBusInterfaceInfo *) &_serial_interface_interface_info.parent_struct;
}

/**
 * serial_interface_override_properties:
 * @klass: The class structure for a #GObject<!-- -->-derived class.
 * @property_id_begin: The property id to assign to the first overridden property.
 *
 * Overrides all #GObject properties in the #SerialInterface interface for a concrete class.
 * The properties are overridden in the order they are defined.
 *
 * Returns: The last property id.
 */
guint
serial_interface_override_properties (GObjectClass *klass, guint property_id_begin)
{
  return property_id_begin - 1;
}



/**
 * SerialInterface:
 *
 * Abstract interface type for the D-Bus interface <link linkend="gdbus-interface-Serial-interface.top_of_page">Serial.interface</link>.
 */

/**
 * SerialInterfaceIface:
 * @parent_iface: The parent interface.
 * @handle_set_air_conditioner_info: Handler for the #SerialInterface::handle-set-air-conditioner-info signal.
 * @handle_set_door_info: Handler for the #SerialInterface::handle-set-door-info signal.
 * @handle_set_key_info: Handler for the #SerialInterface::handle-set-key-info signal.
 * @handle_set_lamp_info: Handler for the #SerialInterface::handle-set-lamp-info signal.
 * @handle_set_speed_info: Handler for the #SerialInterface::handle-set-speed-info signal.
 * @handle_set_start_info: Handler for the #SerialInterface::handle-set-start-info signal.
 * @broadcast_caninfo: Handler for the #SerialInterface::broadcast-caninfo signal.
 *
 * Virtual table for the D-Bus interface <link linkend="gdbus-interface-Serial-interface.top_of_page">Serial.interface</link>.
 */

typedef SerialInterfaceIface SerialInterfaceInterface;
G_DEFINE_INTERFACE (SerialInterface, serial_interface, G_TYPE_OBJECT);

static void
serial_interface_default_init (SerialInterfaceIface *iface)
{
  /* GObject signals for incoming D-Bus method calls: */
  /**
   * SerialInterface::handle-set-door-info:
   * @object: A #SerialInterface.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_arg1: Argument passed by remote caller.
   * @arg_arg2: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-Serial-interface.setDoorInfo">setDoorInfo()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call serial_interface_complete_set_door_info() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-set-door-info",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (SerialInterfaceIface, handle_set_door_info),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    3,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_UINT, G_TYPE_UINT);

  /**
   * SerialInterface::handle-set-lamp-info:
   * @object: A #SerialInterface.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_arg1: Argument passed by remote caller.
   * @arg_arg2: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-Serial-interface.setLampInfo">setLampInfo()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call serial_interface_complete_set_lamp_info() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-set-lamp-info",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (SerialInterfaceIface, handle_set_lamp_info),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    3,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_UINT, G_TYPE_UINT);

  /**
   * SerialInterface::handle-set-key-info:
   * @object: A #SerialInterface.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_arg1: Argument passed by remote caller.
   * @arg_arg2: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-Serial-interface.setKeyInfo">setKeyInfo()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call serial_interface_complete_set_key_info() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-set-key-info",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (SerialInterfaceIface, handle_set_key_info),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    3,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_UINT, G_TYPE_UINT);

  /**
   * SerialInterface::handle-set-speed-info:
   * @object: A #SerialInterface.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_arg1: Argument passed by remote caller.
   * @arg_arg2: Argument passed by remote caller.
   * @arg_arg3: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-Serial-interface.setSpeedInfo">setSpeedInfo()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call serial_interface_complete_set_speed_info() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-set-speed-info",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (SerialInterfaceIface, handle_set_speed_info),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    4,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_UINT, G_TYPE_UINT, G_TYPE_UINT);

  /**
   * SerialInterface::handle-set-air-conditioner-info:
   * @object: A #SerialInterface.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_arg1: Argument passed by remote caller.
   * @arg_arg2: Argument passed by remote caller.
   * @arg_arg3: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-Serial-interface.setAirConditionerInfo">setAirConditionerInfo()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call serial_interface_complete_set_air_conditioner_info() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-set-air-conditioner-info",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (SerialInterfaceIface, handle_set_air_conditioner_info),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    4,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_UINT, G_TYPE_UINT, G_TYPE_UINT);

  /**
   * SerialInterface::handle-set-start-info:
   * @object: A #SerialInterface.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_arg1: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-Serial-interface.setStartInfo">setStartInfo()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call serial_interface_complete_set_start_info() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-set-start-info",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (SerialInterfaceIface, handle_set_start_info),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_UCHAR);

  /* GObject signals for received D-Bus signals: */
  /**
   * SerialInterface::broadcast-caninfo:
   * @object: A #SerialInterface.
   * @arg_candata: Argument.
   * @arg_len: Argument.
   *
   * On the client-side, this signal is emitted whenever the D-Bus signal <link linkend="gdbus-signal-Serial-interface.broadcastCANInfo">"broadcastCANInfo"</link> is received.
   *
   * On the service-side, this signal can be used with e.g. g_signal_emit_by_name() to make the object emit the D-Bus signal.
   */
  g_signal_new ("broadcast-caninfo",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (SerialInterfaceIface, broadcast_caninfo),
    NULL,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_NONE,
    2, G_TYPE_STRING, G_TYPE_UCHAR);

}

/**
 * serial_interface_emit_broadcast_caninfo:
 * @object: A #SerialInterface.
 * @arg_candata: Argument to pass with the signal.
 * @arg_len: Argument to pass with the signal.
 *
 * Emits the <link linkend="gdbus-signal-Serial-interface.broadcastCANInfo">"broadcastCANInfo"</link> D-Bus signal.
 */
void
serial_interface_emit_broadcast_caninfo (
    SerialInterface *object,
    const gchar *arg_candata,
    guchar arg_len)
{
  g_signal_emit_by_name (object, "broadcast-caninfo", arg_candata, arg_len);
}

/**
 * serial_interface_call_set_door_info:
 * @proxy: A #SerialInterfaceProxy.
 * @arg_arg1: Argument to pass with the method invocation.
 * @arg_arg2: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-Serial-interface.setDoorInfo">setDoorInfo()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call serial_interface_call_set_door_info_finish() to get the result of the operation.
 *
 * See serial_interface_call_set_door_info_sync() for the synchronous, blocking version of this method.
 */
void
serial_interface_call_set_door_info (
    SerialInterface *proxy,
    guint16 arg_arg1,
    guint16 arg_arg2,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "setDoorInfo",
    g_variant_new ("(qq)",
                   arg_arg1,
                   arg_arg2),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * serial_interface_call_set_door_info_finish:
 * @proxy: A #SerialInterfaceProxy.
 * @out_unnamed_arg2: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to serial_interface_call_set_door_info().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with serial_interface_call_set_door_info().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
serial_interface_call_set_door_info_finish (
    SerialInterface *proxy,
    gboolean *out_unnamed_arg2,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(b)",
                 out_unnamed_arg2);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * serial_interface_call_set_door_info_sync:
 * @proxy: A #SerialInterfaceProxy.
 * @arg_arg1: Argument to pass with the method invocation.
 * @arg_arg2: Argument to pass with the method invocation.
 * @out_unnamed_arg2: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-Serial-interface.setDoorInfo">setDoorInfo()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See serial_interface_call_set_door_info() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
serial_interface_call_set_door_info_sync (
    SerialInterface *proxy,
    guint16 arg_arg1,
    guint16 arg_arg2,
    gboolean *out_unnamed_arg2,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "setDoorInfo",
    g_variant_new ("(qq)",
                   arg_arg1,
                   arg_arg2),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(b)",
                 out_unnamed_arg2);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * serial_interface_call_set_lamp_info:
 * @proxy: A #SerialInterfaceProxy.
 * @arg_arg1: Argument to pass with the method invocation.
 * @arg_arg2: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-Serial-interface.setLampInfo">setLampInfo()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call serial_interface_call_set_lamp_info_finish() to get the result of the operation.
 *
 * See serial_interface_call_set_lamp_info_sync() for the synchronous, blocking version of this method.
 */
void
serial_interface_call_set_lamp_info (
    SerialInterface *proxy,
    guint16 arg_arg1,
    guint16 arg_arg2,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "setLampInfo",
    g_variant_new ("(qq)",
                   arg_arg1,
                   arg_arg2),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * serial_interface_call_set_lamp_info_finish:
 * @proxy: A #SerialInterfaceProxy.
 * @out_unnamed_arg2: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to serial_interface_call_set_lamp_info().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with serial_interface_call_set_lamp_info().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
serial_interface_call_set_lamp_info_finish (
    SerialInterface *proxy,
    gboolean *out_unnamed_arg2,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(b)",
                 out_unnamed_arg2);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * serial_interface_call_set_lamp_info_sync:
 * @proxy: A #SerialInterfaceProxy.
 * @arg_arg1: Argument to pass with the method invocation.
 * @arg_arg2: Argument to pass with the method invocation.
 * @out_unnamed_arg2: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-Serial-interface.setLampInfo">setLampInfo()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See serial_interface_call_set_lamp_info() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
serial_interface_call_set_lamp_info_sync (
    SerialInterface *proxy,
    guint16 arg_arg1,
    guint16 arg_arg2,
    gboolean *out_unnamed_arg2,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "setLampInfo",
    g_variant_new ("(qq)",
                   arg_arg1,
                   arg_arg2),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(b)",
                 out_unnamed_arg2);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * serial_interface_call_set_key_info:
 * @proxy: A #SerialInterfaceProxy.
 * @arg_arg1: Argument to pass with the method invocation.
 * @arg_arg2: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-Serial-interface.setKeyInfo">setKeyInfo()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call serial_interface_call_set_key_info_finish() to get the result of the operation.
 *
 * See serial_interface_call_set_key_info_sync() for the synchronous, blocking version of this method.
 */
void
serial_interface_call_set_key_info (
    SerialInterface *proxy,
    guint16 arg_arg1,
    guint16 arg_arg2,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "setKeyInfo",
    g_variant_new ("(qq)",
                   arg_arg1,
                   arg_arg2),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * serial_interface_call_set_key_info_finish:
 * @proxy: A #SerialInterfaceProxy.
 * @out_unnamed_arg2: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to serial_interface_call_set_key_info().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with serial_interface_call_set_key_info().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
serial_interface_call_set_key_info_finish (
    SerialInterface *proxy,
    gboolean *out_unnamed_arg2,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(b)",
                 out_unnamed_arg2);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * serial_interface_call_set_key_info_sync:
 * @proxy: A #SerialInterfaceProxy.
 * @arg_arg1: Argument to pass with the method invocation.
 * @arg_arg2: Argument to pass with the method invocation.
 * @out_unnamed_arg2: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-Serial-interface.setKeyInfo">setKeyInfo()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See serial_interface_call_set_key_info() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
serial_interface_call_set_key_info_sync (
    SerialInterface *proxy,
    guint16 arg_arg1,
    guint16 arg_arg2,
    gboolean *out_unnamed_arg2,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "setKeyInfo",
    g_variant_new ("(qq)",
                   arg_arg1,
                   arg_arg2),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(b)",
                 out_unnamed_arg2);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * serial_interface_call_set_speed_info:
 * @proxy: A #SerialInterfaceProxy.
 * @arg_arg1: Argument to pass with the method invocation.
 * @arg_arg2: Argument to pass with the method invocation.
 * @arg_arg3: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-Serial-interface.setSpeedInfo">setSpeedInfo()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call serial_interface_call_set_speed_info_finish() to get the result of the operation.
 *
 * See serial_interface_call_set_speed_info_sync() for the synchronous, blocking version of this method.
 */
void
serial_interface_call_set_speed_info (
    SerialInterface *proxy,
    guint16 arg_arg1,
    guint16 arg_arg2,
    guint16 arg_arg3,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "setSpeedInfo",
    g_variant_new ("(qqq)",
                   arg_arg1,
                   arg_arg2,
                   arg_arg3),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * serial_interface_call_set_speed_info_finish:
 * @proxy: A #SerialInterfaceProxy.
 * @out_unnamed_arg3: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to serial_interface_call_set_speed_info().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with serial_interface_call_set_speed_info().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
serial_interface_call_set_speed_info_finish (
    SerialInterface *proxy,
    gboolean *out_unnamed_arg3,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(b)",
                 out_unnamed_arg3);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * serial_interface_call_set_speed_info_sync:
 * @proxy: A #SerialInterfaceProxy.
 * @arg_arg1: Argument to pass with the method invocation.
 * @arg_arg2: Argument to pass with the method invocation.
 * @arg_arg3: Argument to pass with the method invocation.
 * @out_unnamed_arg3: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-Serial-interface.setSpeedInfo">setSpeedInfo()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See serial_interface_call_set_speed_info() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
serial_interface_call_set_speed_info_sync (
    SerialInterface *proxy,
    guint16 arg_arg1,
    guint16 arg_arg2,
    guint16 arg_arg3,
    gboolean *out_unnamed_arg3,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "setSpeedInfo",
    g_variant_new ("(qqq)",
                   arg_arg1,
                   arg_arg2,
                   arg_arg3),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(b)",
                 out_unnamed_arg3);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * serial_interface_call_set_air_conditioner_info:
 * @proxy: A #SerialInterfaceProxy.
 * @arg_arg1: Argument to pass with the method invocation.
 * @arg_arg2: Argument to pass with the method invocation.
 * @arg_arg3: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-Serial-interface.setAirConditionerInfo">setAirConditionerInfo()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call serial_interface_call_set_air_conditioner_info_finish() to get the result of the operation.
 *
 * See serial_interface_call_set_air_conditioner_info_sync() for the synchronous, blocking version of this method.
 */
void
serial_interface_call_set_air_conditioner_info (
    SerialInterface *proxy,
    guint16 arg_arg1,
    guint16 arg_arg2,
    guint16 arg_arg3,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "setAirConditionerInfo",
    g_variant_new ("(qqq)",
                   arg_arg1,
                   arg_arg2,
                   arg_arg3),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * serial_interface_call_set_air_conditioner_info_finish:
 * @proxy: A #SerialInterfaceProxy.
 * @out_unnamed_arg3: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to serial_interface_call_set_air_conditioner_info().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with serial_interface_call_set_air_conditioner_info().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
serial_interface_call_set_air_conditioner_info_finish (
    SerialInterface *proxy,
    gboolean *out_unnamed_arg3,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(b)",
                 out_unnamed_arg3);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * serial_interface_call_set_air_conditioner_info_sync:
 * @proxy: A #SerialInterfaceProxy.
 * @arg_arg1: Argument to pass with the method invocation.
 * @arg_arg2: Argument to pass with the method invocation.
 * @arg_arg3: Argument to pass with the method invocation.
 * @out_unnamed_arg3: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-Serial-interface.setAirConditionerInfo">setAirConditionerInfo()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See serial_interface_call_set_air_conditioner_info() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
serial_interface_call_set_air_conditioner_info_sync (
    SerialInterface *proxy,
    guint16 arg_arg1,
    guint16 arg_arg2,
    guint16 arg_arg3,
    gboolean *out_unnamed_arg3,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "setAirConditionerInfo",
    g_variant_new ("(qqq)",
                   arg_arg1,
                   arg_arg2,
                   arg_arg3),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(b)",
                 out_unnamed_arg3);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * serial_interface_call_set_start_info:
 * @proxy: A #SerialInterfaceProxy.
 * @arg_arg1: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-Serial-interface.setStartInfo">setStartInfo()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call serial_interface_call_set_start_info_finish() to get the result of the operation.
 *
 * See serial_interface_call_set_start_info_sync() for the synchronous, blocking version of this method.
 */
void
serial_interface_call_set_start_info (
    SerialInterface *proxy,
    guchar arg_arg1,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "setStartInfo",
    g_variant_new ("(y)",
                   arg_arg1),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * serial_interface_call_set_start_info_finish:
 * @proxy: A #SerialInterfaceProxy.
 * @out_unnamed_arg1: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to serial_interface_call_set_start_info().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with serial_interface_call_set_start_info().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
serial_interface_call_set_start_info_finish (
    SerialInterface *proxy,
    gboolean *out_unnamed_arg1,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(b)",
                 out_unnamed_arg1);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * serial_interface_call_set_start_info_sync:
 * @proxy: A #SerialInterfaceProxy.
 * @arg_arg1: Argument to pass with the method invocation.
 * @out_unnamed_arg1: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-Serial-interface.setStartInfo">setStartInfo()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See serial_interface_call_set_start_info() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
serial_interface_call_set_start_info_sync (
    SerialInterface *proxy,
    guchar arg_arg1,
    gboolean *out_unnamed_arg1,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "setStartInfo",
    g_variant_new ("(y)",
                   arg_arg1),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(b)",
                 out_unnamed_arg1);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * serial_interface_complete_set_door_info:
 * @object: A #SerialInterface.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @unnamed_arg2: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-Serial-interface.setDoorInfo">setDoorInfo()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
serial_interface_complete_set_door_info (
    SerialInterface *object,
    GDBusMethodInvocation *invocation,
    gboolean unnamed_arg2)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(b)",
                   unnamed_arg2));
}

/**
 * serial_interface_complete_set_lamp_info:
 * @object: A #SerialInterface.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @unnamed_arg2: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-Serial-interface.setLampInfo">setLampInfo()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
serial_interface_complete_set_lamp_info (
    SerialInterface *object,
    GDBusMethodInvocation *invocation,
    gboolean unnamed_arg2)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(b)",
                   unnamed_arg2));
}

/**
 * serial_interface_complete_set_key_info:
 * @object: A #SerialInterface.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @unnamed_arg2: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-Serial-interface.setKeyInfo">setKeyInfo()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
serial_interface_complete_set_key_info (
    SerialInterface *object,
    GDBusMethodInvocation *invocation,
    gboolean unnamed_arg2)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(b)",
                   unnamed_arg2));
}

/**
 * serial_interface_complete_set_speed_info:
 * @object: A #SerialInterface.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @unnamed_arg3: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-Serial-interface.setSpeedInfo">setSpeedInfo()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
serial_interface_complete_set_speed_info (
    SerialInterface *object,
    GDBusMethodInvocation *invocation,
    gboolean unnamed_arg3)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(b)",
                   unnamed_arg3));
}

/**
 * serial_interface_complete_set_air_conditioner_info:
 * @object: A #SerialInterface.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @unnamed_arg3: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-Serial-interface.setAirConditionerInfo">setAirConditionerInfo()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
serial_interface_complete_set_air_conditioner_info (
    SerialInterface *object,
    GDBusMethodInvocation *invocation,
    gboolean unnamed_arg3)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(b)",
                   unnamed_arg3));
}

/**
 * serial_interface_complete_set_start_info:
 * @object: A #SerialInterface.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @unnamed_arg1: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-Serial-interface.setStartInfo">setStartInfo()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
serial_interface_complete_set_start_info (
    SerialInterface *object,
    GDBusMethodInvocation *invocation,
    gboolean unnamed_arg1)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(b)",
                   unnamed_arg1));
}

/* ------------------------------------------------------------------------ */

/**
 * SerialInterfaceProxy:
 *
 * The #SerialInterfaceProxy structure contains only private data and should only be accessed using the provided API.
 */

/**
 * SerialInterfaceProxyClass:
 * @parent_class: The parent class.
 *
 * Class structure for #SerialInterfaceProxy.
 */

struct _SerialInterfaceProxyPrivate
{
  GData *qdata;
};

static void serial_interface_proxy_iface_init (SerialInterfaceIface *iface);

#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (SerialInterfaceProxy, serial_interface_proxy, G_TYPE_DBUS_PROXY,
                         G_ADD_PRIVATE (SerialInterfaceProxy)
                         G_IMPLEMENT_INTERFACE (TYPE_SERIAL_INTERFACE, serial_interface_proxy_iface_init));

#else
G_DEFINE_TYPE_WITH_CODE (SerialInterfaceProxy, serial_interface_proxy, G_TYPE_DBUS_PROXY,
                         G_IMPLEMENT_INTERFACE (TYPE_SERIAL_INTERFACE, serial_interface_proxy_iface_init));

#endif
static void
serial_interface_proxy_finalize (GObject *object)
{
  SerialInterfaceProxy *proxy = SERIAL_INTERFACE_PROXY (object);
  g_datalist_clear (&proxy->priv->qdata);
  G_OBJECT_CLASS (serial_interface_proxy_parent_class)->finalize (object);
}

static void
serial_interface_proxy_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
}

static void
serial_interface_proxy_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
}

static void
serial_interface_proxy_g_signal (GDBusProxy *proxy,
  const gchar *sender_name G_GNUC_UNUSED,
  const gchar *signal_name,
  GVariant *parameters)
{
  _ExtendedGDBusSignalInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint n;
  guint signal_id;
  info = (_ExtendedGDBusSignalInfo *) g_dbus_interface_info_lookup_signal ((GDBusInterfaceInfo *) &_serial_interface_interface_info.parent_struct, signal_name);
  if (info == NULL)
    return;
  num_params = g_variant_n_children (parameters);
  paramv = g_new0 (GValue, num_params + 1);
  g_value_init (&paramv[0], TYPE_SERIAL_INTERFACE);
  g_value_set_object (&paramv[0], proxy);
  g_variant_iter_init (&iter, parameters);
  n = 1;
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.args[n - 1];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, TYPE_SERIAL_INTERFACE);
  g_signal_emitv (paramv, signal_id, 0, NULL);
  for (n = 0; n < num_params + 1; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static void
serial_interface_proxy_g_properties_changed (GDBusProxy *_proxy,
  GVariant *changed_properties,
  const gchar *const *invalidated_properties)
{
  SerialInterfaceProxy *proxy = SERIAL_INTERFACE_PROXY (_proxy);
  guint n;
  const gchar *key;
  GVariantIter *iter;
  _ExtendedGDBusPropertyInfo *info;
  g_variant_get (changed_properties, "a{sv}", &iter);
  while (g_variant_iter_next (iter, "{&sv}", &key, NULL))
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_serial_interface_interface_info.parent_struct, key);
      g_datalist_remove_data (&proxy->priv->qdata, key);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
  g_variant_iter_free (iter);
  for (n = 0; invalidated_properties[n] != NULL; n++)
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_serial_interface_interface_info.parent_struct, invalidated_properties[n]);
      g_datalist_remove_data (&proxy->priv->qdata, invalidated_properties[n]);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
}

static void
serial_interface_proxy_init (SerialInterfaceProxy *proxy)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  proxy->priv = serial_interface_proxy_get_instance_private (proxy);
#else
  proxy->priv = G_TYPE_INSTANCE_GET_PRIVATE (proxy, TYPE_SERIAL_INTERFACE_PROXY, SerialInterfaceProxyPrivate);
#endif

  g_dbus_proxy_set_interface_info (G_DBUS_PROXY (proxy), serial_interface_interface_info ());
}

static void
serial_interface_proxy_class_init (SerialInterfaceProxyClass *klass)
{
  GObjectClass *gobject_class;
  GDBusProxyClass *proxy_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize     = serial_interface_proxy_finalize;
  gobject_class->get_property = serial_interface_proxy_get_property;
  gobject_class->set_property = serial_interface_proxy_set_property;

  proxy_class = G_DBUS_PROXY_CLASS (klass);
  proxy_class->g_signal = serial_interface_proxy_g_signal;
  proxy_class->g_properties_changed = serial_interface_proxy_g_properties_changed;

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (SerialInterfaceProxyPrivate));
#endif
}

static void
serial_interface_proxy_iface_init (SerialInterfaceIface *iface)
{
}

/**
 * serial_interface_proxy_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-Serial-interface.top_of_page">Serial.interface</link>. See g_dbus_proxy_new() for more details.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call serial_interface_proxy_new_finish() to get the result of the operation.
 *
 * See serial_interface_proxy_new_sync() for the synchronous, blocking version of this constructor.
 */
void
serial_interface_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (TYPE_SERIAL_INTERFACE_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "Serial.interface", NULL);
}

/**
 * serial_interface_proxy_new_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to serial_interface_proxy_new().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with serial_interface_proxy_new().
 *
 * Returns: (transfer full) (type SerialInterfaceProxy): The constructed proxy object or %NULL if @error is set.
 */
SerialInterface *
serial_interface_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return SERIAL_INTERFACE (ret);
  else
    return NULL;
}

/**
 * serial_interface_proxy_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Synchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-Serial-interface.top_of_page">Serial.interface</link>. See g_dbus_proxy_new_sync() for more details.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See serial_interface_proxy_new() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type SerialInterfaceProxy): The constructed proxy object or %NULL if @error is set.
 */
SerialInterface *
serial_interface_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (TYPE_SERIAL_INTERFACE_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "Serial.interface", NULL);
  if (ret != NULL)
    return SERIAL_INTERFACE (ret);
  else
    return NULL;
}


/**
 * serial_interface_proxy_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Like serial_interface_proxy_new() but takes a #GBusType instead of a #GDBusConnection.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call serial_interface_proxy_new_for_bus_finish() to get the result of the operation.
 *
 * See serial_interface_proxy_new_for_bus_sync() for the synchronous, blocking version of this constructor.
 */
void
serial_interface_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (TYPE_SERIAL_INTERFACE_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "Serial.interface", NULL);
}

/**
 * serial_interface_proxy_new_for_bus_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to serial_interface_proxy_new_for_bus().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with serial_interface_proxy_new_for_bus().
 *
 * Returns: (transfer full) (type SerialInterfaceProxy): The constructed proxy object or %NULL if @error is set.
 */
SerialInterface *
serial_interface_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return SERIAL_INTERFACE (ret);
  else
    return NULL;
}

/**
 * serial_interface_proxy_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Like serial_interface_proxy_new_sync() but takes a #GBusType instead of a #GDBusConnection.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See serial_interface_proxy_new_for_bus() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type SerialInterfaceProxy): The constructed proxy object or %NULL if @error is set.
 */
SerialInterface *
serial_interface_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (TYPE_SERIAL_INTERFACE_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "Serial.interface", NULL);
  if (ret != NULL)
    return SERIAL_INTERFACE (ret);
  else
    return NULL;
}


/* ------------------------------------------------------------------------ */

/**
 * SerialInterfaceSkeleton:
 *
 * The #SerialInterfaceSkeleton structure contains only private data and should only be accessed using the provided API.
 */

/**
 * SerialInterfaceSkeletonClass:
 * @parent_class: The parent class.
 *
 * Class structure for #SerialInterfaceSkeleton.
 */

struct _SerialInterfaceSkeletonPrivate
{
  GValue *properties;
  GList *changed_properties;
  GSource *changed_properties_idle_source;
  GMainContext *context;
  GMutex lock;
};

static void
_serial_interface_skeleton_handle_method_call (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name,
  const gchar *method_name,
  GVariant *parameters,
  GDBusMethodInvocation *invocation,
  gpointer user_data)
{
  SerialInterfaceSkeleton *skeleton = SERIAL_INTERFACE_SKELETON (user_data);
  _ExtendedGDBusMethodInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint num_extra;
  guint n;
  guint signal_id;
  GValue return_value = G_VALUE_INIT;
  info = (_ExtendedGDBusMethodInfo *) g_dbus_method_invocation_get_method_info (invocation);
  g_assert (info != NULL);
  num_params = g_variant_n_children (parameters);
  num_extra = info->pass_fdlist ? 3 : 2;  paramv = g_new0 (GValue, num_params + num_extra);
  n = 0;
  g_value_init (&paramv[n], TYPE_SERIAL_INTERFACE);
  g_value_set_object (&paramv[n++], skeleton);
  g_value_init (&paramv[n], G_TYPE_DBUS_METHOD_INVOCATION);
  g_value_set_object (&paramv[n++], invocation);
  if (info->pass_fdlist)
    {
#ifdef G_OS_UNIX
      g_value_init (&paramv[n], G_TYPE_UNIX_FD_LIST);
      g_value_set_object (&paramv[n++], g_dbus_message_get_unix_fd_list (g_dbus_method_invocation_get_message (invocation)));
#else
      g_assert_not_reached ();
#endif
    }
  g_variant_iter_init (&iter, parameters);
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.in_args[n - num_extra];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, TYPE_SERIAL_INTERFACE);
  g_value_init (&return_value, G_TYPE_BOOLEAN);
  g_signal_emitv (paramv, signal_id, 0, &return_value);
  if (!g_value_get_boolean (&return_value))
    g_dbus_method_invocation_return_error (invocation, G_DBUS_ERROR, G_DBUS_ERROR_UNKNOWN_METHOD, "Method %s is not implemented on interface %s", method_name, interface_name);
  g_value_unset (&return_value);
  for (n = 0; n < num_params + num_extra; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static GVariant *
_serial_interface_skeleton_handle_get_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GError **error,
  gpointer user_data)
{
  SerialInterfaceSkeleton *skeleton = SERIAL_INTERFACE_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  GVariant *ret;
  ret = NULL;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_serial_interface_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      g_value_init (&value, pspec->value_type);
      g_object_get_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      ret = g_dbus_gvalue_to_gvariant (&value, G_VARIANT_TYPE (info->parent_struct.signature));
      g_value_unset (&value);
    }
  return ret;
}

static gboolean
_serial_interface_skeleton_handle_set_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GVariant *variant,
  GError **error,
  gpointer user_data)
{
  SerialInterfaceSkeleton *skeleton = SERIAL_INTERFACE_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  gboolean ret;
  ret = FALSE;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_serial_interface_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      if (info->use_gvariant)
        g_value_set_variant (&value, variant);
      else
        g_dbus_gvariant_to_gvalue (variant, &value);
      g_object_set_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      g_value_unset (&value);
      ret = TRUE;
    }
  return ret;
}

static const GDBusInterfaceVTable _serial_interface_skeleton_vtable =
{
  _serial_interface_skeleton_handle_method_call,
  _serial_interface_skeleton_handle_get_property,
  _serial_interface_skeleton_handle_set_property,
  {NULL}
};

static GDBusInterfaceInfo *
serial_interface_skeleton_dbus_interface_get_info (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return serial_interface_interface_info ();
}

static GDBusInterfaceVTable *
serial_interface_skeleton_dbus_interface_get_vtable (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return (GDBusInterfaceVTable *) &_serial_interface_skeleton_vtable;
}

static GVariant *
serial_interface_skeleton_dbus_interface_get_properties (GDBusInterfaceSkeleton *_skeleton)
{
  SerialInterfaceSkeleton *skeleton = SERIAL_INTERFACE_SKELETON (_skeleton);

  GVariantBuilder builder;
  guint n;
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  if (_serial_interface_interface_info.parent_struct.properties == NULL)
    goto out;
  for (n = 0; _serial_interface_interface_info.parent_struct.properties[n] != NULL; n++)
    {
      GDBusPropertyInfo *info = _serial_interface_interface_info.parent_struct.properties[n];
      if (info->flags & G_DBUS_PROPERTY_INFO_FLAGS_READABLE)
        {
          GVariant *value;
          value = _serial_interface_skeleton_handle_get_property (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)), NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "Serial.interface", info->name, NULL, skeleton);
          if (value != NULL)
            {
              g_variant_take_ref (value);
              g_variant_builder_add (&builder, "{sv}", info->name, value);
              g_variant_unref (value);
            }
        }
    }
out:
  return g_variant_builder_end (&builder);
}

static void
serial_interface_skeleton_dbus_interface_flush (GDBusInterfaceSkeleton *_skeleton)
{
}

static void
_serial_interface_on_signal_broadcast_caninfo (
    SerialInterface *object,
    const gchar *arg_candata,
    guchar arg_len)
{
  SerialInterfaceSkeleton *skeleton = SERIAL_INTERFACE_SKELETON (object);

  GList      *connections, *l;
  GVariant   *signal_variant;
  connections = g_dbus_interface_skeleton_get_connections (G_DBUS_INTERFACE_SKELETON (skeleton));

  signal_variant = g_variant_ref_sink (g_variant_new ("(^ayy)",
                   arg_candata,
                   arg_len));
  for (l = connections; l != NULL; l = l->next)
    {
      GDBusConnection *connection = l->data;
      g_dbus_connection_emit_signal (connection,
        NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "Serial.interface", "broadcastCANInfo",
        signal_variant, NULL);
    }
  g_variant_unref (signal_variant);
  g_list_free_full (connections, g_object_unref);
}

static void serial_interface_skeleton_iface_init (SerialInterfaceIface *iface);
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (SerialInterfaceSkeleton, serial_interface_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_ADD_PRIVATE (SerialInterfaceSkeleton)
                         G_IMPLEMENT_INTERFACE (TYPE_SERIAL_INTERFACE, serial_interface_skeleton_iface_init));

#else
G_DEFINE_TYPE_WITH_CODE (SerialInterfaceSkeleton, serial_interface_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_IMPLEMENT_INTERFACE (TYPE_SERIAL_INTERFACE, serial_interface_skeleton_iface_init));

#endif
static void
serial_interface_skeleton_finalize (GObject *object)
{
  SerialInterfaceSkeleton *skeleton = SERIAL_INTERFACE_SKELETON (object);
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    g_source_destroy (skeleton->priv->changed_properties_idle_source);
  g_main_context_unref (skeleton->priv->context);
  g_mutex_clear (&skeleton->priv->lock);
  G_OBJECT_CLASS (serial_interface_skeleton_parent_class)->finalize (object);
}

static void
serial_interface_skeleton_init (SerialInterfaceSkeleton *skeleton)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  skeleton->priv = serial_interface_skeleton_get_instance_private (skeleton);
#else
  skeleton->priv = G_TYPE_INSTANCE_GET_PRIVATE (skeleton, TYPE_SERIAL_INTERFACE_SKELETON, SerialInterfaceSkeletonPrivate);
#endif

  g_mutex_init (&skeleton->priv->lock);
  skeleton->priv->context = g_main_context_ref_thread_default ();
}

static void
serial_interface_skeleton_class_init (SerialInterfaceSkeletonClass *klass)
{
  GObjectClass *gobject_class;
  GDBusInterfaceSkeletonClass *skeleton_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize = serial_interface_skeleton_finalize;

  skeleton_class = G_DBUS_INTERFACE_SKELETON_CLASS (klass);
  skeleton_class->get_info = serial_interface_skeleton_dbus_interface_get_info;
  skeleton_class->get_properties = serial_interface_skeleton_dbus_interface_get_properties;
  skeleton_class->flush = serial_interface_skeleton_dbus_interface_flush;
  skeleton_class->get_vtable = serial_interface_skeleton_dbus_interface_get_vtable;

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (SerialInterfaceSkeletonPrivate));
#endif
}

static void
serial_interface_skeleton_iface_init (SerialInterfaceIface *iface)
{
  iface->broadcast_caninfo = _serial_interface_on_signal_broadcast_caninfo;
}

/**
 * serial_interface_skeleton_new:
 *
 * Creates a skeleton object for the D-Bus interface <link linkend="gdbus-interface-Serial-interface.top_of_page">Serial.interface</link>.
 *
 * Returns: (transfer full) (type SerialInterfaceSkeleton): The skeleton object.
 */
SerialInterface *
serial_interface_skeleton_new (void)
{
  return SERIAL_INTERFACE (g_object_new (TYPE_SERIAL_INTERFACE_SKELETON, NULL));
}

